### ISSUE TITLE
How to connect to open servers?

### ISSUE THREAD

**Issue by timharsch** [smart-on-fhir/client-js#103]
I'm a little confused on how best to connect to open servers and don't see a clear/trivial example in the docs.

According to this: http://docs.smarthealthit.org/client-js/api, I can use SMART.authorize()
![image](https://user-images.githubusercontent.com/61298249/99200890-f1139900-275c-11eb-8eea-fc2dabadc8fc.png)

and then I suppose I would set fhirServiceUri and patientId via:
![image](https://user-images.githubusercontent.com/61298249/99200917-1dc7b080-275d-11eb-8f66-cbf50ac5453d.png).  I tried this in my app, but was having difficulty getting it to work and may need more time to work this out.  Guidance would be appreciated.

Another [part of the docs](http://docs.smarthealthit.org/client-js/) suggests creating the client yourself:
![image](https://user-images.githubusercontent.com/61298249/99200965-6d0de100-275d-11eb-9a6f-460c21f14ab3.png)

which I did (full code here https://gist.github.com/timharsch/6734cdd8e7be10a9bd0e09dd64ab99f1), but then found I could not query via client.patient.read unless I had set the tokenResponse (which seems a little odd as an API, and I'm not sure if this is the intended way).

```javascript
    const _client = client({
      serverUrl: "http://hapi.fhir.org/baseDstu2",
      tokenResponse: { patient: '70079' }
    });
```

Ultimately, what I would like to do is connect to open servers in much the same way I do those that require authentication.   Are there any current examples of connecting to either with the same code?

**Comment by plynchnlm** [comment]
There is an example of setting the patient that same way (tokenResponse) at http://docs.smarthealthit.org/client-js/request.html.  It would be nice for that to be documented as part of the API, though.  (I actually found this issue before I found that example.)

**Comment by timharsch** [comment]
Perhaps the API could be improved by having a setter for patient id? something similar to:

```javascript
    const _client = client({
      serverUrl: "http://hapi.fhir.org/baseDstu2",
    });
   _client.setPatientId(70079)
```

For authenticated cilents the patient Id should probably be read-only, in which case the method could throw an error.

There's already a client `getPatientId()` so it seems a natural fit.

**Comment by vlad-ignatov** [comment]
Sorry for the delayed response. I was busy with other deadlines.

It looks like you were able to properly "discover" how to work with open servers. I agree that this can be confusing and could use a dedicated documentation. I have started that and it is currently available at https://github.com/smart-on-fhir/client-js/blob/master/docs/open_servers.md. It is a work in progress and the examples are not tested yet. Please keep an eye on it and let me know if what I have so far is not clear enough.

**Comment by timharsch** [comment]
Very nice, thank you for taking the time to write the doc page!  It really helps with understanding the two connect modes of client-js and I think it makes a valuable addition to the docs.

So it seems there are two equally valid approaches for open servers.   I suggest for future travelers, that you add some documentation to your new page that would help distinguish the role of fhirServiceUrl vs calling FHIR.client directly, and clarify when you might want to use one or the other.

Something that would have helped me immensely in my journey would have been if the React example that you provided demonstrates two or more servers for connecting, with a mix of authenticated and OPEN servers.  So, I extended it and submitted a proposal for incorporating it into the client-js.  See issue #106.

**Comment by plynchnlm** [comment]
The new documentation says that for open servers, "in rare cases one could be tempted to use client.patient.read() instead of client.request()".  I don't think that is so rare.  I have a SMART app that I also want to use to connect to open servers.  If I can set the patient for the open server (as you document), then I can use the same code for SMART/non-SMART connections.

**Comment by vlad-ignatov** [comment]
Noted and updated! A new version is out now and it includes new way to work with multiple server, also described in http://docs.smarthealthit.org/client-js/open_servers.html
