### ISSUE TITLE
client.getState() needs documentation

### ISSUE THREAD

**Issue by plynchnlm** [smart-on-fhir/client-js#104]
I read about the getState function in https://github.com/smart-on-fhir/client-js/issues/80, but I don't see any documentation for it at http://docs.smarthealthit.org/client-js/client.html.

**Comment by vlad-ignatov** [comment]
Yes, we have somehow forgotten that. It is now added to the docs.

FYI, in case you encounter something else that is not documented, keep in mind that in addition to the manual docs, we also have automatically generated API docs at http://docs.smarthealthit.org/client-js/typedoc/
