### ISSUE TITLE
Extending Advanced React Example

### ISSUE THREAD

**Issue by timharsch** [smart-on-fhir/client-js#106]
When I first found the [Advanced React Example](https://codesandbox.io/s/fhir-client-react-react-router-context-0q3n8) I was very excited because it showed using client-js in React and also showed a few React techniques/concepts.  Since I'm both new to React and to working with Electronic Health Records I found it very helpful.   The example is very visual and relatable since it shows a chart and you can immediately see the value of client-js.  Recently I've had a chance to search out other test servers and experiment with connecting to them.  I thought it might make the React example an improved real world example if it could connect to multiple servers both authenticated and open access, and if it could include Epic and Cerner since a real-world app will likely want to do just that if they are looking to connect to the ~1600 health providers between them.

So I took the Advanced React Example and put it into a stand alone app with the [CRA](https://github.com/facebook/create-react-app), and extended it with a selector to choose from multiple servers, and added a bit of documentation for it.  It's a start..  The front page could probably use a little flare, and the UI of selecting the server leading to an alert box of properties could probably be improved - perhaps the open servers could have a second selector for patients and closed servers could have a list of user/passwords to try.   My thought is that, if you like the direction it's heading then this could be taken into the client-js repo under an "examples/react-fhir-sample-app" directory (perhaps future or current examples could be put in the "examples" directory as well).

react-fhir-sample-app:  https://github.com/Unite-Genomics/react-fhir-sample-app

**Comment by timharsch** [comment]
@vlad-ignatov Do you have any feedback to offer?

**Comment by vlad-ignatov** [comment]
Hi @timharsch,

This looks nice but the truth is I won't be able to dedicate enough tome to `client-js` soon. Also, once I can I have some changes planned that might affect your demo. I want to make it possible to pass multiple configurations and the library should then pick the right one based on the `iss` parameter. Something like:
```js
SMART.authorize([
    {
        iss        : "https://server-1", // exact match
        clientId   : "client-id-at-server-1",
        scope      : "scopes-for-server-1",
        redirectUri: "/redirect-from-server-1"
    },
    {
        iss        : /server-2/, // RegExp match
        clientId   : "client-id-at-server-2",
        scope      : "scopes-for-server-2",
        redirectUri: "./redirect-from-server-2"
    },
    {
        iss        : /open-server/, // no clientId or scope is needed
        redirectUri: "./my-open-server-entry-point"
    },
    {
        iss        : /test-server/, // no clientId or scope is needed
        redirectUri: "./my-test-server-entry-point",
        // other stuff if needed
    }
    // ...
]);
```

Even though that should probably be avoided in production, it would be very helpful in development.

I imagine this can change your example a bit :) Anyway, what I can do right now if you want is that I can add another link in our docs to your repository, because what you have there can currently be used as an example.

**Comment by timharsch** [comment]
Sure.  That would be fine.  Maybe we can consider later on to pull it in to an examples directory in client-js, after it's been updated with your proposed changes.

Thanks!

**Comment by vlad-ignatov** [comment]
A link with text "Running an app against multiple servers" is now added to the home page at http://docs.smarthealthit.org/client-js/

I will close this for now but you can comment later, when we need to revise it. Thanks!
