### ISSUE TITLE
Question: Resource Schema

### ISSUE THREAD

**Issue by QusaiAnthem** [smart-on-fhir/client-js#107]
Is there a way to retrieve a resource schema using client-js?

for example 

```javascript
const patientSchema = await client.patient.readSchema();

if (patientSchema["someField"] === 'dateTime') {
   // grab custom Date renderer for that field?
}
```

thank you for helping me out

**Comment by vlad-ignatov** [comment]
I'm not sure what that resource schema is (which means there is certainly no way to do this). Can you provide more info?

In any case, this is not exactly a FHIR library. It just helps you with authentication and server queries. However, how you process the downloaded data is entirely up to you.

**Comment by QusaiAnthem** [comment]
@vlad-ignatov thank you very much for following up. I apologize for not being clear, with Resource Schema I meant to say if we have an object which we can use to determine the types of data fields for a resource. For example:
Patient.Name is of a type String 
Patient.BDate is of a type Date

We were looking in creating a front-end framework for Fhir Resources management in react. To build views and editable forms on the fly we would need to know field types (i.e schema). For example, if a field is of a date type, we would render a Date react component and so on.

We were wondering if there is a common way to get field types (maybe validation rules also or so) using fhirclient.

Thank you

**Comment by QusaiAnthem** [comment]
never mind got it resolved
