### ISSUE TITLE
Finding respose headers on client.request of observations

### ISSUE THREAD

**Issue by leffle** [smart-on-fhir/client-js#111]
Thank you for your great work.  I like the  client request function for observations, but would also like to examine response headers.  Does the fhir-js-client have this functionality?

Best regards and stay safe!

Louis

**Comment by vlad-ignatov** [comment]
Hi Louis,

This is not currently possible but I've made some changes and it should be doable in the next version. Will keep you posted.

**Comment by leffle** [comment]
Great news Vlad!

This will greatly  improve our error handling routines.

When our EBMcalc FHIR App encounters an error in the Cerner EHR, Cerner engineers will investigate, but they need the request ID code sent in observation response headers.

Best regards and stay safe!

Louis

**Comment by vlad-ignatov** [comment]
The new version (2.3.11) is released!

To access response headers (of any successful request) you need to pass the new `includeResponse` option. See http://docs.smarthealthit.org/client-js/client.html

However, in your case that won't be necessary. If a request fails you will get an `HttpError` object having a `response` property which is a reference to the Response object. This means that something like this should work:
```js
client.request("Observation").catch(error => {
    console.log(error.response.headers.get("x-request-id"));
});
```

**Comment by leffle** [comment]
Awesome!

Thanks Vlad,

Louis

**Comment by leffle** [comment]
Thanks again Vlad,

I understand your code below, but we often need the x-request-id header for successful responses.

We have installed your new library and tried this promise success, failure syntax:

client.request("Observation?" + query, { includeResponse: true })
.then(function(res){ renderData(res); }, function(error){ resourceFail(error); })

And we receive our usual/successful response, but no response headers in the “res” object.

Do we need a promise chain of some sort?

Thanks again,

Louis

**Comment by vlad-ignatov** [comment]
It is not as easy for successful requests unfortunately. I'm not sure if you noticed that in the docs, but:
1. Passing the `includeResponse` changes the return value and your promise will be resolved  with an object like `{response: Response, body: myUsualResult }`
2. `client.request("Observation?" + query, { includeResponse: true })` is wrong. You should do `client.request({ url: "Observation?" + query, includeResponse: true })`

I guess the code you are looking for might look like this:
```js
client.request({ url: "Observation?" + query, includeResponse: true }).then(
    result => {
        console.log(result.response.headers.get("x-request-id"));
        renderData(result.body);
    },
    error => {
        console.log(error.response.headers.get("x-request-id"));
    }
);
```

**Comment by leffle** [comment]
Now that works.  You’re the man Vlad!

Many thanks,

Louis
