### ISSUE TITLE
Propagate HTTP error codes on 401

### ISSUE THREAD

**Issue by josepedrocorreia** [smart-on-fhir/client-js#113]
Hi there,

I am using your library to query FHIR servers, but I am not using your authentication capabilities. I ran into the following problem: if I call `request` and the underlying request to the server returns a 401, this information is being swallowed by your library. What I get is an error with a message ("This app cannot be accessed directly. Please launch it as SMART app!") but without the status code. This is generated in [this line](https://github.com/smart-on-fhir/client-js/blob/ce794fb51df36ebc4b7140278345ed8c52fb866c/src/Client.ts#L786). Not having a code makes it problematic for automatic processing.

What I would like is for the library to propagate the 401 status code for error handling down the line.

Does that make sense?

Cheers

**Comment by vlad-ignatov** [comment]
That does make sense and I am working on a fix that should be released soon. However, this library is not designed to make requests without also handling the authentication, so you might experience other issues after this one is fixed.

**Comment by josepedrocorreia** [comment]
Thanks for the feedback! Looking forward to the update :+1:

**Comment by vlad-ignatov** [comment]
The new version (2.3.11) is now on npm. All http errors should have a `statusCode` and `statusText`, as well as a `response` reference to the `Response` object which you can query for headers and other stuff.

**Comment by josepedrocorreia** [comment]
I can confirm it's working perfectly, thank you very much!
