### ISSUE TITLE
Sending Prefer in Header 

### ISSUE THREAD

**Issue by usmanbahadur** [smart-on-fhir/client-js#123]
When i create new patient and POST data to our FHIR Server i want to be able to send [Prefer](https://build.fhir.org/http.html#ops) options in header, so that I can get response back from Server as explained [here](https://github.com/fhir-crucible/fhir_client/blob/e0f0d4464a55ed38bc77e7380afcd95c39888e8c/README.md).

`patient = FHIR::Patient.new(name: {given: 'John', family: 'Doe'}).create({Prefer: "return=representation"})`

However Client-JS does not have Patient.new option My create new Patient function does the following 

  ` const   AddResource = await FHIR.oauth2.ready().then(client => client.create(values))`

Where `values ` are demographic for new Patient I have tried including `{Prefer: "return=representation"}` into `values` but still no luck. My question is how can i send header when using `client.create` option ?

**Comment by dmhalejr** [comment]
@usmanbahadur 

Looks like the create functionality entry may work appropriately if you just take the `Prefer` options and wrap it in a `headers` object before sending it over.

Found this test that highlights what that create looks like with the given options.

https://github.com/smart-on-fhir/client-js/blob/master/test/Client.test.ts#L3797-L3817

Highlights from the Typescript types for the library:
```
    /**
     * Creates a new resource in a server-assigned location
     * @see http://hl7.org/fhir/http.html#create
     * @param resource A FHIR resource to be created
     * @param [requestOptions] Any options to be passed to the fetch call.
     * Note that `method` and `body` will be ignored.
     * @category Request
     */
    create<R = fhirclient.FHIR.Resource, O extends fhirclient.FetchOptions = {}>(
        resource: fhirclient.FHIR.Resource,
        requestOptions?: O
    ): Promise<O["includeResponse"] extends true ? fhirclient.CombinedFetchResult<R> : R>
    {
        return this.request({
            ...requestOptions,
            url: `${resource.resourceType}`,
            method: "POST",
            body: JSON.stringify(resource),
            headers: {
                // TODO: Do we need to alternate with "application/json+fhir"?
                "Content-Type": "application/json",
                ...(requestOptions || {}).headers
            }
        });
    }
```

I'd still await a main contributor to this library to respond as well but I hope that unblocks you! 👍

**Comment by vlad-ignatov** [comment]
The `create` method signature is `create(data, requestOptions={})`. That means you are looking for something like
```js
create(values, { headers: { prefer: "return=representation" }})
```
