### ISSUE TITLE
Invalid access token

### ISSUE THREAD

**Issue by Koudysmen** [smart-on-fhir/client-js#124]
**Issue**
I am trying to implement Smart on FHIR in my application using Angular and  
I faced problem with authorization. I already registered new provider application in cerner sandbox
Currently I am possible run my application from Cerner sandbox. I guess that authorization process is successful because the server will send the access token back and also redirection working properly, but if I want to use this access token to get patient info from the FHIR server I will retrieve unauthorized response from FHIR server.

Unauthorized response (401):
```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "login",
            "diagnostics": "Bearer realm=\"fhir-ehr-code.cerner.com\", error=\"invalid_token\"",
            "location": [
                "http.Authorization"
            ]
        }
    ]
}
```

**My implementation**
Launch app
```
SMART.authorize({   
      clientId :"bacad00e-2fa4-48a6-9372-26ce70f0d16d",
      scope    : "patient/Patient.read patient/Observation.read launch online_access openid fhirUser",
      redirectUri : "http://localhost:4200/cdslung/?PatientId=12742400",           
  });
```

Index app
```
SMART.ready()
            .then(client => {
                const token = client.getAuthorizationHeader();
                console.log(token);
                client.request(`/Patient/${client.getPatientId()}`);            
            })
            .then(
                (patient) => {
                    console.log(patient);
                },
                error => {
                    console.error(error);
                }); 
```

**Enviroment:** 
Angular CLI: 10.1.3
Node: 10.16.0
OS: win32 x64 
fhirclient 2.3.11

**Comment by SatioO** [comment]
I am facing the similar issue

"HttpError: 401 Unauthorized
URL: https://fhir-ehr-code.cerner.com/dstu2/ec2458f2-1e24-41c8-b71b-0e701af7583d/Patient/12724067

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "login",
            "diagnostics": "Bearer realm=\"fhir-ehr-code.cerner.com\", error=\"invalid_token\"",
            "location": [
                "http.Authorization"
            ]
        }
    ]
}
Session expired! Please re-launch the app
    at checkResponse (http://localhost:3000/static/js/0.chunk.js:11133:19)"
