### ISSUE TITLE
Race condition fetching server metadata

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/client-js#136]
From https://github.com/microsoft-healthcare-madison/client-js/blob/6daa7a5a8db32f2598266130d9c9cce5fcd4a34c/src/smart.ts#L137-L162

this might abort a request to .well-known/smart-configuration if a working /metadata result is found first -- but only a subset of config information is available from `/metadata`. Logically we need to:

* use .well-known/smart-configuration
* (in SMARTv1) fall back to /metadata if .well-known/smart-configuration is unavailable

It should not be a race.

**Comment by vlad-ignatov** [comment]
The client is only looking for `authorization_endpoint` and `token_endpoint` (although it does also "collect" the `registration_endpoint`). Are you saying that there can be a FHIR server that does not include those in its CapabilityStatement, but at the same time does include them in `.well-known/smart-configuration`?

Also note that there are some additional edge cases: https://github.com/smart-on-fhir/client-js/issues/67

**Comment by jmandel** [comment]
Yes, in SMARTv2 we've completed the deprecation and .well-known is the official source of this information -- and even in SMARTv1 for many features `.well-known/smart-configuration` was the *only* way to discover the details (e.g., capabilities; token endpoint auth methods; PKCE challenge methods supported).

**Comment by vlad-ignatov** [comment]
I see. Doing something like `getWellKnown().catch(() => getMetadata()).then(extractInfo)` should be easier than what we are using currently. That may cause some issues (like a server taking 1 minute to reply with 404 for `.well-known/smart-configuration`), but that is not really our problem.

However, the race here is very much separate issue from the SMART v2 support. If you need more artifacts (e.g., capabilities; token endpoint auth methods; PKCE challenge methods supported), then a lot more needs to be changed. It seems to me that this needs to be done in the branch for the SMART2 stuff and merged later.

**Comment by jmandel** [comment]
> Doing something like getWellKnown().catch(() => getMetadata()).then(extractInfo) should be easier than what we are using currently.

Yes.

>However, the race here is very much separate issue from the SMART v2 support

Agreed -- this was already an issue in SMARTv1, but it's more of an issue in SMARTv2; that's why I filed an issue here instead of directly addressing in the SMARTv2 draft PR (but we'll probably implement at spot fix there, at least if people run into real-world issues during connectathon testing.)

**Comment by vlad-ignatov** [comment]
Fixed as part of the SMART v2 changes and released in `v2.5.0`
