### ISSUE TITLE
Using Refresh/RefreshIfNeeded [Help]

### ISSUE THREAD

**Issue by AndrewStoddard** [smart-on-fhir/client-js#138]
Hello,

I am using this to integrate with the Epic EHR and am having an issue when calling refresh. I am getting an error saying that I do not have online_access or offline_access in scope. Upon further investigation, I am requesting online_access, but was informed by a contact at Epic that they return offline_access to the user. However, they do not visibly return it in the scope received. I believe this to be the reason I am receiving the error and have no control over whether or not it is visibly returned. 

Do you have any options for me to still be able to use the refresh token?

**Comment by vlad-ignatov** [comment]
Perhaps your contact at Epic meant that they only support `offline_access`, so try requesting that instead of `online_access`.

**Comment by AndrewStoddard** [comment]
I have tried to explicitly request offline_access, and remove the
online_access, it had no change.

**Comment by isaacvetter** [comment]
https://fhir.epic.com/Documentation?docId=oauth2&section=Standalone-Oauth2-Launch_Access-Token-Request_With-Refresh-Tokens

**Comment by vlad-ignatov** [comment]
Also, I'm not sure if this applies to Epic currently, but in most systems when you register a client you have a list of "allowed scopes". This is to make sure that an app using that client_id cannot be granted wider access than originally intended. If there is something similar on Epic, make sure that the `offline_access` scope is enabled for your client (and then wait whatever amount of time is required for the changes to be applied).

**Comment by vlad-ignatov** [comment]
If it is not an issue with the library I should have it closed (but feel free to continue posting if needed)
