### ISSUE TITLE
Comparison table for FHIR/fhir.js

### ISSUE THREAD

**Issue by fatso83** [smart-on-fhir/client-js#140]
This library seems pretty nice and maintained. Wondering how this compares with FHIR/fhir.js? Not sure what the SMART-on... bit does, but it seems to do a lot of CRUD FHIR stuff at least :)

**Comment by vlad-ignatov** [comment]
- `fhir.js` if what I would call a "request library". It tries to simply building FHIR requests and CRUD operations, but at the price of introducing new mongo-like syntax.
- The `client-js` library is more about the SMART bit. It handles all kinds of authorization flows and launch sequences. Once auth details are out of your way, you get a client object that allows you to do basic CRUD operations agains the FHIR server, WITHOUT using  proprietary syntax.
- Finally, the two libraries can work together. You can use `client-js` as base, and if `fhir.js` is available in the global scope we will detect that and extend the client object with additional capabilities. See https://docs.smarthealthit.org/client-js/#fhirjs-integration

**Comment by fatso83** [comment]
Thanks!
