### ISSUE TITLE
Typescript CROS No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by usmanbahadur** [smart-on-fhir/client-js#141]
hello I am following your example of Typescript [FHIRClient Project](https://codesandbox.io/s/fhir-client-typescript-react-spa-4e7rl?file=/src/index.tsx)  to authenticate against our FHIR service when i run launch through localhost i am getting CORS issue it says no header is present in request resource. 

I have tried two methods. 

method-1
```
import { oauth2 as SMART} from "fhirclient";
SMART.init({ clientId: "myclientid",
            redirect_uri: "http://localhost:19006/",
            iss: "https://azurehealth-fhir.azurehealthcareapis.com" })
```
method-2 
```
import FHIR from 'fhirclient';

 FHIR.oauth2.authorize( clientId: "myclientid",
            redirect_uri: "http://localhost:19006/",
            iss: "https://azurehealth-fhir.azurehealthcareapis.com")
```

The FHIR service works fine with other apps like react-native JavasScript  FHIRClient library. I am only facing CORS with TypeScript, there is no options for send headers any suggestions ? 

`"Access-Control-Allow-Origin", "http://localhost:19006/"`

![image](https://user-images.githubusercontent.com/16957638/144574695-61ef1b4f-87da-416c-9b44-ea69261f4dad.png)

**Comment by madaster97** [comment]
Could you do this again and check your network tab for the "options" call to the smart config endpoint? Curious to see what headers your service is returning

**Comment by usmanbahadur** [comment]
@madaster97  closing the issue after removing the CORS policy from our FHIR service has fixed the problem.
