### ISSUE TITLE
Epic EHR requires signed JWT for authorization for Tesseract but .authorize() does not support overriding default grant_type and assertion

### ISSUE THREAD

**Issue by JordanWinslow** [smart-on-fhir/client-js#145]
This is more of a question than a definitive issue, but let me summarize:

**Epic now requires the backend OAuth flow in order for any app to be approved to their marketplace.** 

Developers must interact with a server called "Tesseract" and present it with a signed JWT token with a modified "aud" parameter in order to authorize as described by the [Epic AppOrchard documentation](https://apporchard.epic.com/Article?docId=oauth2&section=Backend-Oauth2_Access-Token-Request)   (_Sign in Required to View_)

I have scoured every part of the smart-on-fhir docs I could find and read most of the typescript declarations and I am unable to find any way of overriding the default .authorize() behavior to send a POST request from the back end including the following modified formurl encoded body parameters:

```
{...,
grant_type: "client_credentials"
client_assertion_type: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
client_assertion: <SIGNED_JWT_GOES_HERE>
}
```

In addition, to create that signed JWT, I would also need to intercept the response from "/metadata" on the well-known-configuration step so that I can locate the "HSI" value and use it as the "aud" parameter of the above JWT. I am unable to locate a method of intercepting that api call prior to the authorization and redirecting steps in this library.

### Does anyone know how I can accomplish this back end OAuth flow using a signed JWT without me having to remove the fhirclient library from our code and essentially re-write the entire application?

I fear once I remove the .authorize() logic I would also have to remove the .ready() client logic because I wouldn't know how to create a fhir client with this library without using the default .authorize() method and the only reference to creating your own client in the docs seems to assume it is an open server with no authentication required.

Any guidance on this would be greatly appreciated.

**Comment by madaster97** [comment]
@JordanWinslow - are you referring to this new [authorization scheme](http://www.hl7.org/fhir/smart-app-launch/client-confidential-asymmetric.html#client-authentication-asymmetric-public-key)? You'd still be using the SMART App Launch flow, except you'd need to have a code running on a protected web server somewhere.

This library supports both browser-side and server-side (ex: Nodejs) clients, and @jmandel 's Pull Request (#139) will add the ability to use that authentication scheme from a server. This is a fundamentally different use of the library though, where you'd need to have a web server perform the authorization and distribute the necessary data from APIs to your client side.

Want to re-iterate that this new authentication scheme is not itself Backend OAuth/[SMART Backend Services](http://www.hl7.org/fhir/smart-app-launch/index.html#authorization-via-smart-backend-services), it is still an [app launch](http://www.hl7.org/fhir/smart-app-launch/index.html#authorization-via-smart-app-launch), except you are moving portions of the authorization flow out of the browser and onto a server.

**Comment by JordanWinslow** [comment]
@madaster97 It seems similar to that scheme in the sense that it is for a scenario where the client can protect a secret key (ex: back end handles that) and is also similar to the SMART back end services, but I'm not sure if it's the exact scheme you referenced.

Even though the library works on the back end for most scenarios I couldn't find a way of overriding it's default authorization logic to use a signed JWT and the grant_type: "client_credentials" instead of the library's default grant_type: "authorization_code" which seems to be the only type the library supports.

Basically, if a company wants to integrate with Epic and use their Tesseract server for authentication, it requires overriding the default behavior of the fhirclient library to allow different grant_types and the usage of a custom signed JWT using an encrypted private key and uploading the public key to the Epic servers.

Luckily since my company is using a SPA, Epic agreed to remove the Tesseract requirements, but it still may be useful for developers if we can add an override or escape hatch to allow different authentication mechanisms through this library.

Thanks so much for your response!

**Comment by friccita** [comment]
@madaster97  @JordanWinslow
Just to follow up, do you know if such an override has been added to the Smart on Fhir library, or if there are any plans to do so?

**Comment by madaster97** [comment]
@friccita , I've been meaning to respond to this again.

Briefly, if your application includes any sort of web server with a database or business logic, then it doesn't make sense to conduct the OAuth 2.0 flow from your client-side (which is what this library does when used in a single-page app).

Rather, you should be conducting OAuth 2.0 from your backend instead. Finding a nice server OAuth 2.0 server-side SDK is my recommendation. That doesn't mean your front-end can't be a SPA, it just means that the [OAuth 2.0 token request](http://www.hl7.org/fhir/smart-app-launch/app-launch.html#obtain-access-token) should happen on your server, and you should use the result to establish your own session.

@JordanWinslow - Does your application include any sort of backend web server component? How are you generating sessions between your front-end and backend when using OAuth 2.0?

**Comment by dwwinters** [comment]
@JordanWinslow doesn't this PR address your requested feature?
https://github.com/smart-on-fhir/client-js/pull/122

**Comment by madaster97** [comment]
@dwwinters and @JordanWinslow - I don't think there's any issue this library needs to address. If an app needs to use the `client_credentials` grant then there are other libraries available like the openid-client library.

What is relevant is that Epic is recommending that all web-served-based clients use the `private_key_jwt` authentication scheme being introduced in [PR 147](https://github.com/smart-on-fhir/client-js/pull/147). This doesn't mean you need to use `client_credentials`, it just means you would include a `client_assertion` in your request to the token endpoint as discussed [here](http://www.hl7.org/fhir/smart-app-launch/client-confidential-asymmetric.html). 

The vast majority of applications we work with include some sort of web server component, and it's our goal that all those clients move to JWT authentication. We're trying to avoid the situation where an app definitely has a web server but conducts OAuth 2.0 from its frontend instead.

Some references on this topic:

- [IETF Draft: OAuth 2.0 for Browser Based Apps - Section 6.2](http://www.hl7.org/fhir/smart-app-launch/client-confidential-asymmetric.html)
- [A Critical Analysis of Refresh Token Rotation in Single-page applications](https://www.pingidentity.com/en/resources/blog/post/refresh-token-rotation-spa.html) - I love the "Keeping Tokens Out of the Browser" section that talks about the BFF architecture as an alternative
