### ISSUE TITLE
How to send additional headers in FHIR client

### ISSUE THREAD

**Issue by SG-Abhishek-Rawal** [smart-on-fhir/client-js#146]
I need to fetch Binary resource (documents from FHIR) where i need to send additional headers eg: 'Accept': 'application/pdf', how i can send that headers with FHIR client ?

fhirClient.request(`/Binary/41241253645`, {
            headers: {
                Accept: 'application/pdf'
            }
})

this is not working currently, how we can send additional headers?

**Comment by vlad-ignatov** [comment]
That is pretty close. The difference is that the `url` and the options need to go into single object like so:
```ts
fhirClient.request({
    url: '/Binary/41241253645',
    headers: {
        Accept: 'application/pdf'
    }
})
```
