### ISSUE TITLE
Broken links to ServerStorage

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/client-js#148]
Links to https://github.com/smart-on-fhir/client-js/blob/master/src/ServerStorage.js from examples like 

* http://docs.smarthealthit.org/client-js/node#sessions
* https://codesandbox.io/s/brave-wildflower-q4mhq?file=/src/index.js:986-1061

--> should link to https://github.com/smart-on-fhir/client-js/blob/master/src/storage/ServerStorage.ts

**Comment by vlad-ignatov** [comment]
These are fixed now. Thanks!
