### ISSUE TITLE
Unable to authorize using PKCE

### ISSUE THREAD

**Issue by TheZorkij** [smart-on-fhir/client-js#158]
The Code Verifier sent by the app in the token request does not produce a valid Code Challenge. Here is both:
Code Verifier:
```/0T2nBJfBvLbytrymN6TVBNmupxqUEYd4oSJO11MYH9FwZsmE0WUwXHU5oVOwq8QbPZAl1S0vJp9FmCWSYPJmaoI3J8762QkXB+dRywfMFCYG5e1+wFpEYB6W2q7xC6O```

Code Challenge from the authorization request:
```jFtUhY/me1ri0Y5qAMJN7TbBpkpTKqSmbabxzkxO3 k=```

[RFC7636](https://datatracker.ietf.org/doc/html/rfc7636#section-4.1) says that a Code Verifier must only contain unreserved characters ```[A-Z] / [a-z] / [0-9] / "-" / "." / "_" / "~"``` but this one contains '+' and '/' which can't be right?

**Comment by vlad-ignatov** [comment]
Should be fixed in `fhirclient@2.5.2`. Please re-open if you have further issues.
