### ISSUE TITLE
fhir-client.js failed on unsecured/open client

### ISSUE THREAD

**Issue by yunwwang** [smart-on-fhir/client-js#16]
When using the latest fhir-client.js (v 0.1.11) with unsecured client (client that doesn't do Oauth2), BBClient.ready() function failed at line 17167. The reason is that unsecured client doesn't have access_token. So the payloadCheck object is null and the code section at line 17167 payloadCheck['exp'] crashes the process.

When I say unsecured client, I mean the client that bypass OAuth2 authentication. The server url is send to launch page using fhirServiceUrl parameter.

Environment: Windows 7 , VS 2015, MVC ASP.NET 4.5.2, fhir-client.js 0.1.11

**Comment by zplata** [comment]
@yunwwang Can you try now with the latest fhir-client file? It's in the `master` branch but I don't think a version update has occurred yet.

**Comment by nschwertner** [comment]
Addresed in https://github.com/smart-on-fhir/client-js/commit/202d4545156471145d52b23dad0c45f92a4c3402
