### ISSUE TITLE
Support refresh token and apply refresh token automatically to requests when needed

### ISSUE THREAD

**Issue by kolkheang** [smart-on-fhir/client-js#17]
It would be a great enhancement to add logic to retrieve and apply refresh token to outgoing FHIR calls automatically when the token expiration is nearing or when the token is expired.

**Comment by interopion** [comment]
Addresed in https://github.com/smart-on-fhir/client-js/commit/83cc200ca4df8ef573db9c0de4540f0429de631c

**Comment by nschwertner** [comment]
Addressed in https://github.com/smart-on-fhir/client-js/commit/83cc200ca4df8ef573db9c0de4540f0429de631c

**Comment by kolkheang** [comment]
@nschwertner - that commit above from @zplata only for when the app is refreshed/reloaded.  The issue that I logged here is different.  This is to check if the token is expired and if so, get a refresh token for the incoming request for all requests.

**Comment by vlad-ignatov** [comment]
This is handled slightly differently in `v2`. When any request receives 401 and there is a refresh token, new access token is requested using the refresh token. Then the failed request is repeated and we proceed as usual...

I am closing this issue now. Please open new one if the new refresh flow does not work properly for you.
