### ISSUE TITLE
Node js After 10 min 401 unauthorized response

### ISSUE THREAD

**Issue by raginibaptist** [smart-on-fhir/client-js#171]
Hello Team,

We are using fhirclient 2.5.1 version.

we are facing an issue with fhir API in the Cerner application. 
After 10 mins our application is not working and we are getting unauthorized from the API.

the code is written in node js. please help us to resolve this issue. 

Thanks in advance.

**Comment by vlad-ignatov** [comment]
Hi @raginibaptist,

That sounds quite normal actually. Apps rely on a short session and have to be re-launched when it expires. To avoid that:

1. In your client settings in Cerner you need to make sure your client is allowed to ask for `offline_access` or `online_access` scope.
2. Then in your code make sure you request one of those scopes

**Comment by raginibaptist** [comment]
@vlad-ignatov Thanks for you response. where should i pass this scope ? 
  
await fhirclient.oauth2.authorize(config);
scope : offline_access user/Patient.read user/Condition.read user/MedicationRequest.read 

i'm passing the scope like this but not getting refreshtoken 

and if i am calling fhirready method again it is returning same invalid token how could i generate new token in same session using fhirclient 

Please help me.

**Comment by vlad-ignatov** [comment]
You should pass the scopes you are requesting at the `authorize` call. 

A NodeJS example could like like this:
```js
const smart  = require("fhirclient");


// If successful, this will authorize and then redirect to /app
app.get("/launch", (req, res, next) => {
    smart(req, res)
        .authorize({
            clientId   : "my_web_app",
            redirectUri: "/app",
            scope      : "launch patient/*.read openid fhirUser offline_access"
        })
        .catch(next);
}

app.get("/app", async (req, res, next) => {
    smart(req, res)
        .ready()
        .then(client => client.request("Patient").then(res.json))
        .catch(next);
});
```

In this example you request `/app` and it should work fine for a while. At some point your access token will expire (or will be close enough to its expiration). In that case `client.request` will detect that and will silently renew your token before fetching and returning the patients. 

That is all, but it will only work if you add `offline_access` or `online_access` to the scopes you request with `authorize`, and if your client is configured to allow that on Cerner.

Hope that helps.

**Comment by raginibaptist** [comment]
Thanks @vlad-ignatov this code worked for me.
