### ISSUE TITLE
Support of PKCE even when the EHR .well-known configuration is not set?

### ISSUE THREAD

**Issue by vincehartman38** [smart-on-fhir/client-js#174]
During the authorization workflow to use PKCE, it appears the `code_challenge_method` is set when it calls https://{base-url}/.well-known/smart-configuration. If code_challenge_methods_supported does not return anything, then the code_challenge is not included in the auth call and there appears to be an assumption then that PKCE is not supported. 

We confirmed that AthenaHealth currently has PKCE enabled, but this link does not have the code_challenge_method set in the response: [https://api.preview.platform.athenahealth.com/fhir/r4/.well-known/smart-configuration](https://api.preview.platform.athenahealth.com/fhir/r4/.well-known/smart-configuration)

Is there anyway to force the smart-on-fhir authorization function to still use a code_challenge_method of S256 when you have tested and confirmed that the EHR supports it, even though they haven't set it up in their well-known/smart-configuration response? It seems setting the parameter `pkceMode="required"` doesn't in fact do this.

I might be mistake in all this, looking for insight. Thanks!

**Comment by vlad-ignatov** [comment]
In situations like this you can set the “pkceMode” options to “unsafeV1”. Still, the proper solution is to push on AthenaHealth to fix their well-known configuration statement.
