### ISSUE TITLE
Assumption on patient id in context

### ISSUE THREAD

**Issue by jkiddo** [smart-on-fhir/client-js#176]
Isn't https://github.com/smart-on-fhir/client-js/blob/8f64b770dbcd0abd30646e239cd446dfa4d831f6/src/Client.ts#L247 this a somewhat strong assumption. AFAIK the patientId is not required to be present in the access token.

**Comment by vlad-ignatov** [comment]
It is not an assumption. It is a method which you can always call, but it will only succeed if the patient is available. Otherwise it will reject with "Patient is not available" error.
