### ISSUE TITLE
TypeError: Cannot read property 'substr' of undefined at stripTrailingSlash

### ISSUE THREAD

**Issue by dwilhel1** [smart-on-fhir/client-js#22]
I receive a somewhat vague error when using this client to communicate with an auth server:

>TypeError: Cannot read property 'substr' of undefined at stripTrailingSlash

From what I can tell, this is caused by `fhirServiceUrl` missing a value. Would it be possible to catch for an error here, and produce a more useful error message?

**Comment by bhupesh-sf** [comment]
I am facing the same. Any solution yet?

**Comment by kperveen** [comment]
It worked for me by putting a `/` at the end of launch url.

**Comment by bhupesh-sf** [comment]
This is the line being called
`var server = urlParam("iss") || urlParam("fhirServiceUrl");`
And inside urlParam() function 
`var query = location.search.substr(1);
  var data = query.split("&");
  var result = [];

  for(var i=0; i<data.length; i++) {
    var item = data[i].split("=");
    if (item[0] === p) {
      var res = item[1].replace(/\+/g, '%20');
      result.push(decodeURIComponent(res));
    }
  }`
And query is always empty so it is returning undefined as location.search has nothing.

**Comment by bhupesh-sf** [comment]
@kperveen When I put `/` at the end of URL it gives 404

**Comment by ivanlebed** [comment]
Ran into this issue when following the cerner tutorial :/ https://engineering.cerner.com/smart-on-fhir-tutorial/#app-launch

**Comment by lmiller1990** [comment]
I too am having this problem

**Comment by vlad-ignatov** [comment]
Sorry for the late reply. This should be fixed in `fhirclient@0.1.15`. If the launch URL is not loaded properly the launch will fail, but instead of showing such useless errors, there will be a warning in the console:
![screenshot_20190125_125543](https://user-images.githubusercontent.com/1119082/51765905-22facd80-20a7-11e9-98dd-6672324def53.png)
