### ISSUE TITLE
Update jqFhir.js library to include the latest version @ https://github.com/FHIR/fhir.js

### ISSUE THREAD

**Issue by kolkheang** [smart-on-fhir/client-js#24]
The [current fhir.js library](https://github.com/smart-on-fhir/client-js/blob/master/lib/jqFhir.js) being included is not the latest version @ https://github.com/FHIR/fhir.js which supports `Accept` header [override](https://github.com/FHIR/fhir.js/blob/master/src/fhir.js#L32).

**Comment by kolkheang** [comment]
@nschwertner  - any plan to update the fhir.js library?

**Comment by nschwertner** [comment]
We will look into it, but I don't have a definitive timeline to share just yet

**Comment by kolkheang** [comment]
Thanks @nschwertner.  It would be great to use the new functionality in fhir-client.js library.  Developers want to have an ability to set custom accept http headers.

**Comment by col-panic** [comment]
There was a recent patch for the search operator in https://github.com/FHIR/fhir.js/issues/120, could you please provide an up to date fhirclient (0.1.13?) (installable via npm) that includes this patch? 

thanks a lot

**Comment by vlad-ignatov** [comment]
The latest fhir.js is included in `fhirclient@0.1.15`
