### ISSUE TITLE
Using fhirclient with vue.js

### ISSUE THREAD

**Issue by col-panic** [smart-on-fhir/client-js#25]
Hy there,

I am currently trying to use fhirclient with vue.js, much like described in https://developer.okta.com/blog/2018/02/15/build-crud-app-vuejs-node for tps://github.com/okta/okta-oidc-js. 

Has anybody realized such a scenario, any hints on how tho use fhirclient this way?

Thanks a lot!

**Comment by stfnh** [comment]
@col-panic I created a sample app with Vue.js, you can check it out here: https://github.com/stfnh/bb-clear-smart-fhir

**Comment by col-panic** [comment]
Thats great - thanks a lot for all the infos resp. the sample!

**Comment by col-panic** [comment]
@stfnh that is really an excellent example! Thanks a lot!

**Comment by EthelEz** [comment]
> https://github.com/stfnh/bb-clear-smart-fhir

Hi @stfnh I'm new in vue, thank you for posting this example. 

I'm trying to figure out how you got the medication-tile></medication-tile in App.vue file. 

Please do you want to share?
