### ISSUE TITLE
Unsupported FHIR range operators

### ISSUE THREAD

**Issue by combatentropy** [smart-on-fhir/client-js#32]
This library's range operators are: `lt`, `lte`, `gt`, and `gte` (https://github.com/smart-on-fhir/client-js/blob/master/lib/jqFhir.js#L565). Two of those aren't standard (`lte` and `gte`). Instead FHIR has `le` and `ge` (https://www.hl7.org/fhir/search.html#prefix). It has more, too, if you want to implement those.

**Comment by col-panic** [comment]
This was also discussed in https://github.com/FHIR/fhir.js/issues/120 where a resp. patch was provided - I would very much welcome a new version of this client with this patch contained.

**Comment by vlad-ignatov** [comment]
This should be fixed in `fhirclient@0.1.15` which includes the latest fhir.js
