### ISSUE TITLE
Support Authorization Workflow in a New Window

### ISSUE THREAD

**Issue by kolkheang** [smart-on-fhir/client-js#33]
The current authorization workflow only support authorization flow in the same window.  It does not support launching a new window for the authorization flow.

The library should allow the authorization flow to be done in a separate window for a better user experience; and also to support a use case where the app is embedded in an iframe.  During the authorization flow, the server may present an authorization request to the user.  If the application is embedded in an iframe, the user will not be able to see the authorization request due to the X-Frame-Options header.

The consumers of this library should have the ability to specify whether the authorization flow should be in a new window or embedded using the same window.

**Comment by vlad-ignatov** [comment]
I am happy to announce that this has finally been addressed and released in `2.3.0`. If the authorization flow cannot be loaded into the specified frame or window (e.g.: popups are blocked) it should continue in the same window as usual. For more info see:
- http://docs.smarthealthit.org/client-js/api.html#advanced-options
- http://docs.smarthealthit.org/client-js/targets.html
- https://fmv99.csb.app/

It is a new feature, yet to be verified in practice. I hope you might be one of the first to try it out.

I am closing this now and you can open another issue for specific problems with this implementation, if you have any.

**Comment by kolkheang** [comment]
Thanks @vlad-ignatov!
