### ISSUE TITLE
Refresh token call needs with credentials

### ISSUE THREAD

**Issue by jpdimond** [smart-on-fhir/client-js#37]
In addition to issue #17, making the client apply refresh tokens automatically, my collaborator @rmchndrng had to create a fork to add withCredentials to support the refresh workflow here: https://github.com/rmchndrng/client-js/commit/17d765710e854f9402b6bc50e92cef8c8db9df5c

Thank you for all of your work on this!

We are currently trying to use your JS library for a large scale RCT trial out of Columbia. :)

**Comment by vlad-ignatov** [comment]
I am closing this as no longer relevant. The library was rewritten in `v2` and the refresh flow is different. We do have a `credentials: "include"` flag in the refresh `fetch` call. Feel free to reopen if you have similar issue with version >= `2.2.0`.
