### ISSUE TITLE
Errors while retrieving refresh and/or access token

### ISSUE THREAD

**Issue by BS062721** [smart-on-fhir/client-js#40]
We're developing smart app using **react** & **fhir-client** and we are seeing following errors if user doesn't interact with app for long time.

1. 'failed to exchange code for access_token'
2. 'Failed to exchange refresh token for access token' 

They are not that frequent but it would be nice if there's any workaround with this errors rather than having user relaunch the application.

CC: @vlad-ignatov

**Comment by vlad-ignatov** [comment]
Please try the latest version. It is a complete rewrite and fixes a lot of issues. Basically, if you have a refresh token, you app should be usable for the life-time of that refresh token.

I am closing this issue now, but feel free to reopen if you have similar issues with the new version.
