### ISSUE TITLE
Await + onPage together

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/client-js#45]
```
await client.request("/Patient", {
    pageLimit: 5,
    onPage(bundle) {
        // do something with the downloaded page
    }
});
```

What does the outer `await` eventually return? An array of pages? There are some docs below but it'd be good to include (with comments) in this snippet some use of the returned array.

> If onPage returns a promise it will be awaited for.

This isn't quite clear: waited for at what stage?

> To fetch all the available pages you can set this to 0

If I use `pageLimit: 0` and `onPage`, do all the results still get aggregated into an (arbitrarily large) in-memory array to resolve the top-level promise?

**Comment by vlad-ignatov** [comment]
Thanks, I'll see how these examples can be improved. Note that the `await ` prefix in some cases is just a short version of saying "this returns a promise". I can remove that if you  find it confusing.

- What does the outer await eventually return?  - returns `null` if `onPage` is used. It only makes sense to await if you want to know when all pages are done. Also, any errors should propagate to the outer promise. Then await will throw, or you can use `.catch()` instead.
- If onPage returns a promise it will be awaited for - this was supposed to mean that the library will wait for `onPage` to resolve before fetching the next page.
- If I use pageLimit: 0 and onPage, do all the results still get aggregated into an (arbitrarily large) in-memory array to resolve the top-level promise? - No. You should get `null` from the outer promise if you use `onPage`.

**Comment by vlad-ignatov** [comment]
There a re more docs (https://docs.smarthealthit.org/client-js/) and examples now, so I guess I can close this one.
