### ISSUE TITLE
Explain relation to fhir.js

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/client-js#46]
> Since v2.0.0 this library no longer includes fhir.js. That architecture was extremely difficult to maintain. However, it is still possible to use fhir.js.

Is fhir.js needed, or is the equivalent/relevant functionality already available in this library? It would be good to say something like "there is no need to use fhir.js; the necessary functionality comes built in to the SMART client" if that's the case.

**Comment by vlad-ignatov** [comment]
It would be ideal if we could say that! For now though, I still have try what part of fhir.js can be reproduced without it. In any case, I would like to keep it as "plugin" for backwards compatibility. We do not intend to replicate that Mongo syntax anyway, so those who prefer that should include fhir.js.

**Comment by jmandel** [comment]
OK -- then to be clear, does a user *need* to load their own copy of fhir.js to use this library? If so, then we should say that. (As written now, it sounds optional.)

**Comment by vlad-ignatov** [comment]
Oh, Yes! The documentation is yet to be completed, especially regarding the fhir.js integration.

It is definitely optional. However, if the user wants to use the legacy APIs like `client.api.whatever()` and `client.patient.api.whatever()`, then he must add "fhir.js" to the page.

**Comment by vlad-ignatov** [comment]
Should be explained a little better now - https://docs.smarthealthit.org/client-js/#fhirjs-integration
