### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by DanielASAndrews** [smart-on-fhir/client-js#47]
@vlad-ignatov Thank you so much for the great work recently on this lib!! 🥇 

Have you published the package yet? ```npm i client-js``` fails and I don't see client-js in the npm registry

**Comment by vlad-ignatov** [comment]
I have not! I am preparing to release it. The code is mostly ready, but I'm currently writing docs and examples (we will need those because this is a big change: http://docs.smarthealthit.org/client-js/v2.html).

I guess you could `npm install` it from GitHub if you just want to give it a try.

**Comment by DanielASAndrews** [comment]
Ty for the update, will do that in mean time - didn't know I could do something like that 👍
