### ISSUE TITLE
conformance fetch failing  on auth server default content type of application/xml

### ISSUE THREAD

**Issue by ssmillard** [smart-on-fhir/client-js#52]
Authentication server has a default content type of application/xml.  fhir-client is expecting json.

**Comment by vlad-ignatov** [comment]
We don't support XML but it should be possible to avoid this one. Can you please provide more details:

- What is the request
   - Does it have an `accept` header
   - What is the full URL requested
- What response are getting back
- What error are you getting

**Comment by ssmillard** [comment]
The error is in the when it is retrieving the conformance statement.  I think adding an accept header will fix the problem.  

 Error: Uncaught (in promise): Error: Failed to fetch the conformance statement from "/metadata". SyntaxError: Unexpected token < in JSON at position 0
Error: Failed to fetch the conformance statement from "/metadata". SyntaxError: Unexpected token < in JSON at position 0
    at fhir-client.js:10588

**Comment by vlad-ignatov** [comment]
Thanks @ssmillard! Can you send me the full URL of the conformance statement?
I am asking because I want to try different requests against it.

The client should be sending an accept header of `application/json`, but maybe that is not good enough for that server.

**Comment by ssmillard** [comment]
https://open-ic.epic.com/Argonaut/api/FHIR/Argonaut/metadata.  I also had tested this in postman.  no header returns xml.  accept header of application/json returns json.

**Comment by vlad-ignatov** [comment]
Same here. The metadata endpoint returns JSON if accept header of application/json is sent.

However, the client should also be sending that header (assigned [here](https://github.com/smart-on-fhir/client-js/blob/master/src/lib.js#L51)). It seems to work for me. Are you using the latest version `2.0.7`?

**Comment by ssmillard** [comment]
That was the issue.  I was pinned to an earlier version.  Sorry about that.

**Comment by msohaib308** [comment]
I am having same issue.

fhirClient is expecting JSON format but fhir server is returning XML
here is the fhir server URLs

https://staging-fhir.ecwcloud.com/fhir/r4/FFBJCD/metadata
https://staging-fhir.ecwcloud.com/fhir/r4/FFBJCD/.well-known/smart-configuration

Fhir server provide extra query parameter "_format=json" to get JSON response, this option is only for metadata
but they did not provide this option for "smart-configuration" end point 

I don't know how to set this ("_format=json" ) configuration in fhirCLient Library.

https://staging-fhir.ecwcloud.com/fhir/r4/FFBJCD/metadata?_format=json

![Screenshot 2023-03-31 124304](https://user-images.githubusercontent.com/42337255/229056683-de9d8f87-082d-4e87-9e52-34ce8b4a7d2d.png)

Is there any option to accept XML responses
