### ISSUE TITLE
Refresh token needs offline access scope to work?

### ISSUE THREAD

**Issue by maloykr** [smart-on-fhir/client-js#60]
Hi --

I was using v2 in a webapp ... but when i call client.refresh() I get following error:

Uncaught Error: Unable to refresh. No offline_access scope found.

I was looking to refresh the token when the webapp is left open (I think Cerner's tokens last about 9.5 minutes or something)

Is there a way to refresh the token in webapp ... or do you need offline scope?  

Thanks,
kevin.

**Comment by vlad-ignatov** [comment]
Your app works by using an **access token** to authenticate on each request (the one that will last ~ 9.5 minutes).

If you do request an `offline_access` scope (and if the server supports that), then you will be given another token called `refresh token`. That is what will allow you to make those refresh calls.

Note that you typically don't have to call client.refresh(). Just add that scope and let client.request() to do it's thing.
