### ISSUE TITLE
response body (eg OperationOutcome) not made available for failed requests

### ISSUE THREAD

**Issue by lawley** [smart-on-fhir/client-js#65]
If a request fails - eg 4xx errors, the response body may contain valuable information (eg as an OperationOutcome), but this is not passed through in the error object

**Comment by vlad-ignatov** [comment]
This shouldn't happen. Perhaps you are using an old version of the library? If not, can you please provide some example or instructions on how to reproduce?

**Comment by vlad-ignatov** [comment]
This appears to be an issue with an old and no longer supported version of the library. As such, I am closing it but feel free to re-open if that is not the case.
