### ISSUE TITLE
on hapi server, redirectUri always set to http, never https

### ISSUE THREAD

**Issue by krinchai** [smart-on-fhir/client-js#69]
I'm working on app orchard integration using hapi js server (fhirclient@2.2.0) and found that the requst makes to the authorize endpoint with the redirectUri with http scheme. I took a look at the code and found that the issue was from NodeAdapter.js, line 56 where the req.protocol is always undefined for the hapi server. the possosible solution is to add the use of this._request.url.protocol for the hapi server.

**Comment by vlad-ignatov** [comment]
Good catch! Should be fixed in `2.3.0`. Please let me know if that works for you.

**Comment by krinchai** [comment]
It works!!! I like your fix, using the socket info. Thanks!

**Comment by vlad-ignatov** [comment]
Thank you!
