### ISSUE TITLE
resolveReferences not works in nested array

### ISSUE THREAD

**Issue by mjawabrah** [smart-on-fhir/client-js#73]
organization sample 

{
  "resourceType": "Organization",
  "id": "1",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2020-02-06T02:21:21.768-05:00"
  },
  "identifier": [
    {
      "use": "official",
      "type": {
        "text": "License"
      },
      "value": "PS002",
      "period": {
        "start": "2019-01-01T00:00:00.000Z",
        "end": "2025-12-31T23:59:59.000Z"
      },
      "assigner": {
        "reference": "Organization/2"
      }
    }
  ],
  "active": false,
 
  "name": "test Org"
}

I trying to load  resource (organization) contains multiple  identifier inside each identifier entity assigner (I need to load all identifier assigner ) 

-----
I pass option 
 resolveReferences: ["identifier.assigner"]

 return references: {}

**Comment by mjawabrah** [comment]
but if i pass resolveReferences: ["identifier.0.assigner"] its return single  reference, but i need to return all references

**Comment by vlad-ignatov** [comment]
That is correct. References are specified using a dot-separated path like `identifier` or `identifier.0. assigner`. What you are looking for would look like `identifier[all]. assigner` but such expressions are not supported (and are more or less beyond the scope of this library).

What you can do is use `resolveReferences : "identifier"` to get all the identifiers and then transform them like so:
```js
const assigners = references.map(x => x. assigner);
```

**Comment by ahmadnairat** [comment]
where should I put this:
"const assigners = references.map(x => x.assigner);"
because after

**Comment by vlad-ignatov** [comment]
Are you trying to this for single organization, or for all organizations on the server, or for several organizations that you have filtered somehow?

**Comment by mjawabrah** [comment]
For Single organization I need to show organization details and inside organization details I display organization information (name , ...) and  table  Listing   identifiers and for each identifier I need to display who the assigner(assigner organization name).

**Comment by vlad-ignatov** [comment]
Well, it looks like there is no simple way to do this. I may consider augmenting those paths to support some basic expressions, but it is not going to happen soon. Until then, you would have to fetch your orgs manually. That might look like this (I've not tested this code):

```js
client.request("Organization/orgID").then(org => {

    // For each identifier (if any)
    return Promise.all((org.identifier || []).map(o => {

        // If this identifier includes assigner.reference
        const ref = client.getPath(o, "assigner.reference");
        if (ref) {

            // fetch the reference and mount the result "assigner"
            return client.request(ref).then(result => o.assigner = result);
        }

        // If no assigner.reference is found resolve and continue
        return o;
    }))

    // return the (possibly modified) organization
    .then(() => org);
}).then(org => {
    // org should have identifier[..].assigner set to the resolved objects
});```

**Comment by bradcurfman** [comment]
Vlad, did you add the above functionality into the library to retrieve all references in the array? The documentation for resolveReferences() indicates you can leave off the index value to have all references in the array resolved. But I can only get the resolve to work when I specify an index.
http://docs.smarthealthit.org/client-js/client.html

**Comment by vlad-ignatov** [comment]
To be clear, the docs state that you can use `identifier` to get all identifiers (if they were references), or `identifier.0` to get the first one.  Your case is a little different, bu I understand why you need it.

In the latest version (2.3.8) I added support for the `..` path operator to allow paths like `identifier..assigner`, which will match if identifier is an array of objects having an assigner reference property. This should finally solve you case.
