### ISSUE TITLE
Client.create Methods returns body, Can we get response headers as well?

### ISSUE THREAD

**Issue by muzZziii** [smart-on-fhir/client-js#76]
I have created a new Resource with Client (eg: DocumentReference) now the resource server returns null in body but gives Location of created resource in header params,

![image](https://user-images.githubusercontent.com/27478777/75136721-5aeb9e80-5707-11ea-8417-b74818e5785a.png)

Is there any way now to read the value from response headers?

**Comment by vlad-ignatov** [comment]
The fix is now released in `2.3.5`. Feel free to reopen if it does not solve the issue.
