### ISSUE TITLE
TypeError: getRef(...).then is not a function

### ISSUE THREAD

**Issue by boganov** [smart-on-fhir/client-js#77]
Hi! Started using the library in the React Native project today and run into a problem with resolveReferences. This is the request:
`client.request('Encounter', {pageLimit: 0, flat: true, resolveReferences['subject']})`
And suddenly request crashes when getRef returns result object instead of a promise. Looks like it's a fetch caching thing and promise resolves faster than loop finishes resolving references. Here is the stack trace:
> TypeError: getRef(...).then is not a function
>     at eval (Client.js:111)
>     at Array.map (<anonymous>)
>     at resolveRef (Client.js:107)
>     at eval (Client.js:178)
>     at Array.map (<anonymous>)
>     at eval (Client.js:177)
>     at tryCallOne (core.js:37)
>     at core.js:123
>     at JSTimers.js:289
>     at _callTimer (JSTimers.js:146)

What am I doing wrong and how to fix this?
Not sure if this will help but is it possible to ignore fetch caching for all requests? Seems like setting headers for client.request doesn't inherit to subsequent requests for resolving references.

**Comment by vlad-ignatov** [comment]
I think this may be fixed in the latest development version. Can you give it a try? To do so use `npm i fhirclient@dev` or use the bundle from https://combinatronics.com/smart-on-fhir/client-js/master/dist/build/fhir-client.js

**Comment by vlad-ignatov** [comment]
Should be fixed now. Feel free to re-open if it doesn't work for you.
