### ISSUE TITLE
fakeTokenResponse not working

### ISSUE THREAD

**Issue by kellermartin13** [smart-on-fhir/client-js#78]
I am trying to utilize the fakeTokenResponse documented here: http://docs.smarthealthit.org/client-js/api.html
```
FHIR.oauth2.authorize({
	'response_type': 'code',
	'clientId': clientId,
	'redirectUri': redirectUri,
	'state': generateStateValue(),
	'fakeTokenResponse': fakeTokenResponse, // Object with data
	'scope': 'launch online_access openid profile launch/patient patient/Patient.read'
});
```

However, the tokenResponse I receive is an actual tokenResponse, not the fake token that I created. There is not much documentation on this option, and I can't find examples of anyone else using it. Am I doing this correctly?

I'd like to be able to insert this token so that I can use my own test data as a response, instead of the token I receive from the client.

**Comment by vlad-ignatov** [comment]
1. Add the `fhirServiceUrl` option as @lhdmulder pointed out and make sure you don't pass an `iss` option. That will tell the `authorize` function that it is a "fake" launch and it should skip the auth server and redirect straight to `fhirServiceUri`.
2. There is no `state` option for authorize.

If you can summarize exactly what are the confusing parts are, I can try to improve those in the docs.

**Comment by vlad-ignatov** [comment]
This is not an issue so I am closing it. Feel free to re-open if you have problems with it.
