### ISSUE TITLE
aud parameter

### ISSUE THREAD

**Issue by jsannerstedt** [smart-on-fhir/client-js#79]
Is there a reason why aud is always set to the server url? Would it be possible to extend the options for authorize to manually set aud?

**Comment by vlad-ignatov** [comment]
Yes, that is part of the spec: http://www.hl7.org/fhir/smart-app-launch/

- For EHR launch that happens dynamically via the `iss` parameter that the EHR passes to your launch endpoint.
- For standalone launch you define that yourself by setting the `iss` option in your `authorize` call, which is probably what you are asking about.

**Comment by vlad-ignatov** [comment]
I am closing this now since there is nothing to do here. Feel free to re-open if you have an actual issue with this library.
