### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by lhdmulder** [smart-on-fhir/client-js#84]
I was wondering if and how this wonderful library deals with binaries, such as referred to by DocumentReference resources?

**Comment by vlad-ignatov** [comment]
There is no special treatment. Consider this example for fetching (and displaying in browser) a PDF file:

```js
FHIR.client("https://r2.smarthealthit.org")
    .request("Binary/smart-Binary-1-document")
    .then(res => res.blob())
    .then(blob => {
        const frame = document.createElement("iframe");
        document.body.appendChild(frame);
        frame.src = URL.createObjectURL(blob);
    });
```

**Comment by vlad-ignatov** [comment]
This is not an issue so I am closing it. Feel free to re-open if you have problems with binaries.
