### ISSUE TITLE
Anyone else getting an invalid_grant from new fhir.epic.com auth schema with jwt auth_code?

### ISSUE THREAD

**Issue by maloykr** [smart-on-fhir/client-js#87]
Hi --

Might be just me, but Epic's new authorization_code with a jwt instead of an opaque code won't let me retrieve an access_token (instead I am getting { "error": "invalid_grant",  "error_description": null} from the token endpoint for their sandbox)

Anyone else having same issue with new sandbox using fhir-client v2?

Thanks,
kevin

**Comment by vlad-ignatov** [comment]
Hi @maloykr,

Are you still having this issue? If so, can you provide some instructions on how to reproduce it?

**Comment by vlad-ignatov** [comment]
Closing due ti inactivity. Feel free to reopen if needed.
