### ISSUE TITLE
How to end the user session

### ISSUE THREAD

**Issue by JoyDJ** [smart-on-fhir/client-js#91]
I am using FHIR.oauth2.authorize() to authorize the provider. What is the suggested approach to end the user session?

**Comment by vlad-ignatov** [comment]
I think there is no good way to do that. Some auth servers may have a dedicated "logout" endpoint, but that is not standard as far as I know.

With that said, the assumption here is that you don't really need to do that. The access is granted based on access tokens that are very short lived (typically about 10 minutes). When you are done with an app, you can just close it and your session will expire soon after that. Furthermore, this library stores it's state, including the access token and the refresh token (if any) in SessionStorage. This means that if you close the window or tab, the state is cleared.

**Comment by vlad-ignatov** [comment]
I am closing this now since there is nothing to do here. Feel free to re-open if you have an actual issue with this library.
