### ISSUE TITLE
What is the sequence of commands used to publish this library to npm?

### ISSUE THREAD

**Issue by bradcurfman** [smart-on-fhir/client-js#93]
I forked this project to merge the PKCE from https://github.com/smart-on-fhir/client-js/issues/72 and used the sequence of commands from the README to build the package. I setup a GitHub package to have a private repo with the changes and then published the library into the private GitHub package using:
npm publish

But when I install the version from my private package and start my React app, I get a compile error of 
Module not found: Can't resolve 'fhirclient' in '/(removed path)/patient-application/src'

If I try to use npm link to locally link to the modified code, I get the same error. I was able to work around this for linking by changing to the 'dist' folder and running npm link from there.

**Comment by bradcurfman** [comment]
I figured this out.

You have to run 'npm publish' from the 'dist' folder.

**Comment by vlad-ignatov** [comment]
Glad to hear it. I intend to address #72 somehow but I'm not there yet.
