### ISSUE TITLE
Unable to write Unit test cases for FHIR client methods

### ISSUE THREAD

**Issue by Abhinav4952** [smart-on-fhir/client-js#95]
I am using the React testing library and jest for my unit testing ,I was unable to mock FHIR methods.
Below is my code where i am using FHIR methods:-
`  FHIR.oauth2
       .ready()
      .then((client) =>
        client.request("ExplanationOfBenefit?patient=Patient/" + patient_id, {
          // client.request({url: "ExplanationOfBenefit", headers: {Accept: '*/*'}}, {
          resolveReferences: [
            "provider",
            "patient",
            "facility",
            "claim",
            "insurer",
          ],
          graph: true,
        })
      )
      .then((json) => {
        console.log(json);
        
      })
      .catch(console.error);`

When I am writting unit test cases for the component I am getting below error:-
`    TypeError: Cannot read property 'ready' of undefined

      121 |     const patient_id = sessionStorage.getItem("patient_id");
      122 |     FHIR.oauth2
    > 123 |       .ready()`

I am mocking the FHIR methods using 
jest.mock('fhirclient',()=>({
    ready:jest.fn(()=>Promise.resolve({data:null}))
}))

Can I get any help in this issue.I am unable to mock these methods

**Comment by vlad-ignatov** [comment]
It appears that the library is not available in your tests (`FHIR.oauth2 = undefined`). Did you import it somehow?

**Comment by Abhinav4952** [comment]
> It appears that the library is not available in your tests (`FHIR.oauth2 = undefined`). Did you import it somehow?

Yes I imported the FHIR library with the below snippet:-
```
import FHIR from "fhirclient";
jest.mock('fhirclient',()=>({     ready:jest.fn(()=>Promise.resolve({data:null})) }))
```
ive even tried by mocking the ready and oauth2

**Comment by vlad-ignatov** [comment]
I'm sorry but this is a little confusing. Can you provide (or link to) the whole file?

Also note that this might simply be impossible. The library won't work properly outside of it's native environment (browser or node). For example. `FHIR.oauth2.ready()` will only succeed if called in a web page that has the proper URL parameters set up, which happens after the EHR redirects to it, and if you have DOM and SessionStorage... I have written a lot of tests for it, but that involves mocking a lot of things and using the underlying pieces from the `src` folder. See  https://github.com/smart-on-fhir/client-js/blob/master/test/Client.test.ts

**Comment by Abhinav4952** [comment]
> I'm sorry but this is a little confusing. Can you provide (or link to) the whole file?
> 
> Also note that this might simply be impossible. The library won't work properly outside of it's native environment (browser or node). For example. `FHIR.oauth2.ready()` will only succeed if called in a web page that has the proper URL parameters set up, which happens after the EHR redirects to it, and if you have DOM and SessionStorage... I have written a lot of tests for it, but that involves mocking a lot of things and using the underlying pieces from the `src` folder. See https://github.com/smart-on-fhir/client-js/blob/master/test/Client.test.ts

here is the snippet for my test cases all the possibilities which I tried to mock the FHIR methods(some of them are kept in comments):-
`
import {Services} from "../services.component"
import React, { Component } from "react";

import { render } from '@testing-library/react';

import '@testing-library/jest-dom/extend-expect'
import FHIR, { oauth2 } from "fhirclient";

const mockoauth2=oauth2;
const mockFHIR=FHIR;
// jest.mock('fhirclient',()=>{FHIR:{oauth2:{ready:jest.fn(()=>Promise.resolve({data:null}))}}});
jest.mock('fhirclient',()=>{ready:jest.fn(()=>Promise.resolve({data:null}))})
jest.mock('fhirclient',()=>{oauth2:jest.fn(()=> '')})
jest.mock('fhirclient',()=>{FHIR:jes.fn(()=>mockoauth2)})
// jest.mock('fhirclient',()=>{FHIR:()=>{return mockoauth2}})
// jest.mock('fhirclient', () => ({ready: jest.fn(()=>Promise.resolve({data:null}))}))
test('renders as expected', () => {
    
    render(<Services></Services>)
});`


And yes I went all through ur test cases how u are mocking ,I felt that u are mocking ur server calls my mocking a server,but i was unable to achieve the same when i am doing using jest and react testing library

**Comment by vlad-ignatov** [comment]
It seems to me that this is a different topic. It is not an issue with this library. Instead, the question is how to properly mock stuff with Jest.

I don't have a lot of experience with Jest so I won't be able to give you good advice, but I can share my thoughts in general.

1. What you are trying to do (judging by your examples) is nearly impossible. You would have to mock a lot of things, including a DOM, sessionStorage etc. Even if you manage to do that, you will then need a dedicated FHIR server to provide those responses...
2. Your examples look like you are trying to test the library. I don't need to do that. It is already tested. You need to test your own business logic instead.

With that said, I would recommend that you follow this approach:

If your real code looks like
```js
FHIR.oauth2.ready().then((client) =>
    client.request("ExplanationOfBenefit?patient=Patient/" + patient_id, {
    resolveReferences: [
        "provider",
        "patient",
        "facility",
        "claim",
       "insurer",
    ],
    graph: true,
}))
.then(handleExplanationOfBenefit)
.catch(console.error);
```
then you only need to test your own `handleExplanationOfBenefit` function:
```js
// Create a mock function like
function getExplanationOfBenefit() {
    return Promise.resolve({ resourceType: "ExplanationOfBenefit", ... })
}

// then use it to test your code:
getExplanationOfBenefit().then(handleExplanationOfBenefit);
```

Or even a more generic version:
```js
function fetchResource(json) {
    return Promise.resolve(json)
}

// then use it to test your code:
fetchResource({ resourceType: "ExplanationOfBenefit", ... }).then(handleExplanationOfBenefit);
fetchResource({ resourceType: "Patient", ... }).then(handlePatient);
...
```

I hope that helps.

**Comment by vlad-ignatov** [comment]
This is not an issue so I am closing it. Feel free to re-open if you have problems with it.
