### ISSUE TITLE
Connect using an established access token

### ISSUE THREAD

**Issue by bpetty-formfast** [smart-on-fhir/client-js#99]
After reading the API documentation for using the api server side, the documentation states that ready() is meant to be called after authorize(...).  That works perfectly.  There are no examples, however, of creating a new client instance server side and making a simple call with it when hitting a secondary endpoint.

I am trying to figure out how to use this library with the access token I was given and url information... that should be enough.
My callback (redirect_uri) is a node endpoint, not a browser page.  My web services are also on different servers than my client code.  I assume for this library to work I'd have to somehow set cookies on my client with all of that session information manually... and pass a "state" param for the "ready" call to generate another client instance.

Am I missing something?  That seems way too complicated... I simply want to create a client using a url and access toke (and maybe a refresh token if it will auto refresh for me).

**Comment by vlad-ignatov** [comment]
I'm not sure I understand your question(s) very well. Anyway, there are several server-side examples in the "Table of Contents" at http://docs.smarthealthit.org/client-js/. Lets consider the Express one at https://codesandbox.io/s/jovial-dew-c0che?file=/src/index.js. There is a `handler` function that will simply emit some JSON response to the client. If I understand correctly, you want to call some additional web services from other domains before replying to the clients. In this case you can do something like:
```js
async function handler(client, res) {
    const patient = await client.patient.read();
    
    // Call other services (pseudo code) - augment patient with additional data from my DB
    const additions = await getOtherPatientDetails();
 
    res.json({ ...patient, ...additions });
} 
```
If that is not what you are looking for, please clarify by splitting this into multiple questions if needed.

**Comment by bpetty-formfast** [comment]
Sorry, I may not have been that clear.

Given an access token and server url, how can I create a client instance using this library?

**Comment by vlad-ignatov** [comment]
Short form useful for open servers:
```js
const client = new FHIR.client("https://r3.smarthealthit.org");
```

Long form:
```js
const client = new FHIR.client(options);
```
where `options` is described at https://github.com/smart-on-fhir/client-js/blob/master/src/types.d.ts#L243-L327

I think you are looking for:
```js
const client = new FHIR.client({
    serverUrl: "...",
    tokenResponse: {
        access_token: "..."
    }
});
```

**Comment by vlad-ignatov** [comment]
Correction! That was for browsers. On the server do:
```js
const smart   = require("fhirclient");

app.get("/app", (req, res) => {
    smart(req, res).client(options);
});
```

**Comment by bpetty-formfast** [comment]
Thank you @vlad-ignatov !  That is exactly what I was looking for.
I have one slight tangential question:  I am also setting the refresh_token property.  I had read that if set the client will automatically refresh if/when the access token expires.  Am I understanding that correctly, or is there anything else I need to configure?

**Comment by vlad-ignatov** [comment]
Well, you are obviously doing some non-standard stuff so it is hard to tell. I'd say that you can just try and see if it does refresh for you.

Basically, you need to authorize and then obtain the `state` from your storage and pass it to the `client()` factory function (instead of `options` in the above example). That `state` should contain everything you need, including the `serverUrl`, the `access_token`, the `refresh_token` if you have one and the `expiresAt` timestamp which is needed for the proper auto-refresh, and the `id_token` if you got one which provides your `fhirUser`.

I think what you are looking for might look like this:
```js
// Server A ----------------------------------------------------------------------------------------------
const smart = require("fhirclient");
app.get("/app", (req, res) => {
    // assuming that there is a post request function with signature post(url: string, body: object): Promise<object> 
    smart(req, res).ready().then(client => post("ServerB/patient", client.getState()).then(res.json));
});

// Server B ----------------------------------------------------------------------------------------------
const smart = require("fhirclient");
app.post("/patient", (req, res) => smart(req, res).client(req.body).request("Patient").then(res.json));


```

**Comment by bpetty-formfast** [comment]
Thanks again.  I had to set "expiresAt" equal to the access token's exp value, set the scope to "online_access", and then set the tokenUri in order to get the auto-refresh to work.

**Comment by vlad-ignatov** [comment]
Great! Just be aware that depending on what EHR you connect to, your access token may be just a random string (instead of JWT) and it won't have an `exp` value. The proper way to do that would be to use the `expires_in` property of the token response.
